server {
    listen 80;
    server_name cyber.finrisk.sogaz.ru;

    location /chat/ {
        alias /usr/share/nginx/html/;
    }

    location ~ ^(/|/chat)$ {
        return 301 http://$http_host/chat/;
    }

    location = /health/readiness {
        return 200 '{"status": "ready"}';
        add_header Content-Type application/json;
    }

    location = /health/liveness {
        return 200 '{"status": "alive"}';
        add_header Content-Type application/json;
    }
}